---
  - name: "Update packages"
    become: true
    apt:
      update_cache: yes
  
  - name: "upgrade package"
    become: true
    apt:
      upgrade: yes
  
  - name: "Installing nodejs and npm"
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes
  
  - name: "Install pm2"
    become: true
    npm:
      name: "pm2"
      state: present
      global: true
      production: yes

  
