---
  - name: "Print working directory"
    shell: |
      pwd

  - name: "Extract the zipped artifact into the EC2 instance"
    unarchive:
      remote_src: yes
      src: ../../backend/artifact.tar.gz
      dest: /home/ubuntu

  - name: "Start app"
    shell: |
      cd /home/ubuntu/backend
      npm install
      pm2 stop default
      pm2 start npm -- start

